project_id           = "your-gcp-project-id"
region               = "us-central1"
zone                 = "us-central1-a"
app_port             = "8080"
ssh_user             = "ubuntu"
ssh_public_key_path  = "~/.ssh/id_rsa.pub"
